ClassicGarage/Controllers/CarModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClassicGarage.DAL;
using ClassicGarage.Models;
using Microsoft.AspNet.Identity;

namespace ClassicGarage.Controllers
{
    public class CarModelsController : Controller
    {
        private GarageContext db = new GarageContext();

        // GET: CarModels
        public ActionResult Index()
        {
            var car = db.Car.Include(c => c.Owner);
            return View(car.ToList());
        }

        // GET: CarModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModel carModel = db.Car.Find(id);
            if (carModel == null)
            {
                return HttpNotFound();
            }
            return View(carModel);
        }

        // GET: CarModels/Create
        public ActionResult Create()
        {
            //ViewBag.OwnerID = new SelectList(db.Owner, "ID", "FirstName");
            return View();
        }

        // POST: CarModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Create([Bind(Include = "ID,Brand,Model,Year,VIN,Series,Photo,Buy_Date,Sell_Date,Buy_Cost,Sell_Cost,OwnerID")] CarModel carModel)
        {
           string main = Server.MapPath("~/Content/Photo/");
            var e_mail = User.Identity.GetUserName();
            var firstname = db.Owner.Where(s => s.EMail == e_mail).Select(s => s.FirstName).FirstOrDefault();
            var lastname  = db.Owner.Where(s => s.EMail == e_mail).Select(s => s.LastName).FirstOrDefault();

            string source = firstname + lastname+"\\";

            var TargetLocation = Path.Combine(main, source);
            if (ModelState.IsValid)
            {
                HttpPostedFileBase postedFile = Request.Files["Photo"];

              
                    if (postedFile.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(postedFile.FileName);
                        var path = Path.Combine(TargetLocation, fileName);
                        postedFile.SaveAs(path);
                    carModel.Photo = fileName;
                    }
               
               

                db.Car.Add(carModel);
                db.SaveChanges();
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
        
     

            //ViewBag.OwnerID = new SelectList(db.Owner, "ID", "FirstName", carModel.OwnerID);
            return View(carModel);
        }

        // GET: CarModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModel carModel = db.Car.Find(id);
            if (carModel == null)
            {
                return HttpNotFound();
            }
            // ViewBag.OwnerID = new SelectList(db.Owner, "ID", "FirstName", carModel.OwnerID);
            return View(carModel);
        }

        // POST: CarModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Brand,Model,Year,VIN,Series,Photo,Buy_Date,Sell_Date,Buy_Cost,Sell_Cost,OwnerID")] CarModel carModel)
        {
            string main = Server.MapPath("~/Content/Photo/");
            var e_mail = User.Identity.GetUserName();
            var firstname = db.Owner.Where(s => s.EMail == e_mail).Select(s => s.FirstName).FirstOrDefault();
            var lastname = db.Owner.Where(s => s.EMail == e_mail).Select(s => s.LastName).FirstOrDefault();

            string source = firstname + lastname + "\\";

            var TargetLocation = Path.Combine(main, source);
            if (ModelState.IsValid)
            {
                HttpPostedFileBase postedFile = Request.Files["Photo"];


                if (postedFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(postedFile.FileName);
                    var path = Path.Combine(TargetLocation, fileName);
                    postedFile.SaveAs(path);
                    carModel.Photo = fileName;
                }

                db.Entry(carModel).State = EntityState.Modified;
                db.SaveChanges();
               return RedirectToAction(nameof(HomeController.Index), "Home");
            }
            //ViewBag.OwnerID = new SelectList(db.Owner, "ID", "FirstName", carModel.OwnerID);
            return View(carModel);
        }

        // GET: CarModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModel carModel = db.Car.Find(id);
            if (carModel == null)
            {
                return HttpNotFound();
            }
            return View(carModel);
        }

        // POST: CarModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CarModel carModel = db.Car.Find(id);
            //biore wszystkie id 
            var temp = db.Repair.Where(p => p.CarID == id);
            foreach (var item in temp)
            {
                //bierzemy wszystkie czesci dla danej naprawy
                var part = db.Parts.Where(x => x.RepairID == item.ID);
                //ustawiamy na nulle wszystkie repair id
                    foreach(var item_1 in part)
                            {
                                 item_1.RepairID = null;
                            }
             
            }
            //kasujemy naprawy
                 db.Repair.RemoveRange(db.Repair.Where(x => x.CarID == id)).Select(p=>p.ID);
            
            db.Car.Remove(carModel);
            db.SaveChanges();
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClassicGarage/Controllers/HomeController.cs
using ClassicGarage.DAL;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClassicGarage.Models;
using System.Data;
using System.Data.Entity;
using System.Net;

namespace ClassicGarage.Controllers
{
    public class HomeController : Controller
    {
        private GarageContext db = new GarageContext();
        public ActionResult Index() 
        {
            
            var e_mail = User.Identity.GetUserName();
            var query = db.Owner.Where(s => s.EMail == e_mail).Select(s => s.ID).FirstOrDefault();
            Session["UserID"] = query;
            var car = db.Car.Include(p => p.Owner).Where(p=>p.OwnerID==query);
            var notice_exist = db.Notice.Include(p => p.Active).Where(p => p.Car.OwnerID == query).Where(p=>p.Active==true).Count();
            if(notice_exist>=1)
            {
                ViewBag.Notice = true;
            }
            //Console.WriteLine(string.Join(", ", cars));

            return View(car.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ClassicGarage/Controllers/NoticeModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClassicGarage.DAL;
using ClassicGarage.Models;
using Microsoft.AspNet.Identity;

namespace ClassicGarage.Controllers
{
    public class NoticeModelsController : Controller
    {
        private GarageContext db = new GarageContext();
        //GET : NoticeModels/AllNotice
        public ActionResult AllNotice()
        {
            var notice = db.Notice.Include(n => n.Car).Include(n => n.Car.Owner).Where(n=>n.Active==true);
            return View(notice.ToList());
        }

        // GET: NoticeModels/5
        public ActionResult Index()
        {
            var temp =(int)Session["UserID"];
            var notice = db.Notice.Include(n => n.Car).Include(n => n.Car.Owner).Where(n => n.Car.Owner.ID == temp);
            return View(notice.ToList());
        }

        // GET: NoticeModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           //var temp = (int)Session["UserID"];
            var notice = db.Notice.Include(n => n.Car).Include(n => n.Car.Owner).Where(n => n.ID == id);
            if (notice == null)
            {
                return HttpNotFound();
            }
            return View(notice.ToList());
        }

        // GET: NoticeModels/Create
        public ActionResult Create()
        {
            var temp = (int)Session["UserID"];
            ViewBag.CarID = new SelectList(db.Car.Where(p=>p.OwnerID==temp), "ID", "Brand");
            return View();
        }

        // POST: NoticeModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CarID,Description,Active,Price,Photo")] NoticeModel noticeModel)
        {
            string main = Server.MapPath("~/Content/Photo/");
            var e_mail = User.Identity.GetUserName();
            var firstname = db.Owner.Where(s => s.EMail == e_mail).Select(s => s.FirstName).FirstOrDefault();
            var lastname = db.Owner.Where(s => s.EMail == e_mail).Select(s => s.LastName).FirstOrDefault();

            string source = firstname + lastname + "\\";

            var TargetLocation = Path.Combine(main, source);
            if (ModelState.IsValid)
            {
                HttpPostedFileBase postedFile = Request.Files["Photo"];
                if (postedFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(postedFile.FileName);
                    var path = Path.Combine(TargetLocation, fileName);
                    postedFile.SaveAs(path);
                    noticeModel.Photo = fileName;
                }
                else
                {
                    
                }
              
            }

            db.Notice.Add(noticeModel);
            db.SaveChanges();
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        // GET: NoticeModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NoticeModel noticeModel = db.Notice.Find(id);
            if (noticeModel == null)
            {
                return HttpNotFound();
            }
            var temp = (int)Session["UserID"];
            ViewBag.CarID = new SelectList(db.Car.Where(p=>p.OwnerID==temp), "ID", "Brand", noticeModel.CarID);
            return View(noticeModel);
        }

        // POST: NoticeModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CarID,Description,Active,Price,Photo")] NoticeModel noticeModel)
        {
            if (ModelState.IsValid)
            {
                string main = Server.MapPath("~/Content/Photo/");
                var e_mail = User.Identity.GetUserName();
                var firstname = db.Owner.Where(s => s.EMail == e_mail).Select(s => s.FirstName).FirstOrDefault();
                var lastname = db.Owner.Where(s => s.EMail == e_mail).Select(s => s.LastName).FirstOrDefault();

                string source = firstname + lastname + "\\";

                var TargetLocation = Path.Combine(main, source);
                if (ModelState.IsValid)
                {
                    HttpPostedFileBase postedFile = Request.Files["Photo"];
                    if (postedFile.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(postedFile.FileName);
                        var path = Path.Combine(TargetLocation, fileName);
                        postedFile.SaveAs(path);
                        noticeModel.Photo = fileName;
                    }

                }
                db.Entry(noticeModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarID = new SelectList(db.Car, "ID", "Brand", noticeModel.CarID);
            return View(noticeModel);
        }

        // GET: NoticeModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NoticeModel noticeModel = db.Notice.Find(id);
            if (noticeModel == null)
            {
                return HttpNotFound();
            }
            return View(noticeModel);
        }

        // POST: NoticeModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NoticeModel noticeModel = db.Notice.Find(id);
            db.Notice.Remove(noticeModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClassicGarage/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ClassicGarage/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ClassicGarage/Views/Home/Index.cshtml
@model IEnumerable<ClassicGarage.Models.CarModel>
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Home Page";
}


@if (Request.IsAuthenticated)
{
    <br />




    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col"> @Html.DisplayNameFor(model => model.Photo)</th>
                <th scope="col">  @Html.DisplayNameFor(model => model.Brand)</th>
                <th scope="col">  @Html.DisplayNameFor(model => model.Model)</th>
                <th scope="col">  @Html.DisplayNameFor(model => model.Year)</th>
                <th scope="col">Szczegoly</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="thumbnail">
                        <img src="@Url.Content("~/Content/Photo/"+item.Owner.FirstName+item.Owner.LastName+"/"+item.Photo)" alt="..." class="img-responsive">
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Brand)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Year)
                    </td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                Akcja
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li>@Html.ActionLink("Szczegoly", "Details", "CarModels", new { id = item.ID }, null)</li>
                                <li>@Html.ActionLink("Edytuj", "Edit", "CarModels", new { id = item.ID }, null)</li>
                                <li>@Html.ActionLink("Naprawy", "Repairs", "RepairModels", new { id = item.ID }, null)</li>

                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Usuń", "Delete", "CarModels", new { id = item.ID }, null)</li>
                            </ul>
                        </div>
                    </td>
                </tr>

            }


        </tbody>
    </table>


    @Html.ActionLink("Dodaj nowe auto", "Create", "CarModels", null, new { @class = "btn btn-primary btn-lg" })
    @Html.ActionLink("Dodaj Ogłoszenie", "Create", "NoticeModels", null, new { @class = "btn btn-primary btn-lg" })
    @Html.ActionLink("Lista części", "Index", "PartsModels", null, new { @class = "btn btn-primary btn-lg" })
    <br />
   
        @Html.ActionLink("Ogłoszenia", "Index", "NoticeModels", null, new { @class = "btn btn-primary btn-lg" })
  




    //<img src="@Url.Content("~/Content/img/img.jpg")" alt="..." class="img-thumbnail">
    <!--
    <div class="row">

          <th class="thumbnail"><img src="@Url.Content("~/Content/Img/img.jpg")" alt="..." class="img-thumbnail"></th>
        <div class="col-md-4">

            <h2>Dodaj nowe auto </h2>
            <p>
                Dodaj auto
            </p>

            <a class="btn btn-default" href='@Url.Action("Create", "CarModels")'>Click &raquo;</a>
            <a class="btn btn-default" href='@Url.Action("Index", "CarModels")'>Spojrz istniejace &raquo;</a>
        </div>

        <div class="col-md-4">

            <h2>Dodaj nowe czesci  </h2>
            <p>
                części
            </p>

            <a class="btn btn-default" href='@Url.Action("Create", "PartsModels")'>Click &raquo;</a>
            <a class="btn btn-default" href='@Url.Action("Index", "PartsModels")'>Spojrz istniejace &raquo;</a>
        </div>
        <div class="row">
            <div class="col-md-4">
                <h2>Dodaj nowe ogloszenie</h2>
                <p>
                    Dodaj ogloszenie do bazy ale cos nie dziala dziwne (narazie tylko po wybraniu ID)
                </p>

                <a class="btn btn-default" href='@Url.Action("Create", "NoticeModels")'>Click &raquo;</a>
                <a class="btn btn-default" href='@Url.Action("Index", "NoticeModels")'>Spojrz istniejace &raquo;</a>
            </div>
            <div class="col-md-4">
                <h2>Dodaj nowe naprawe</h2>
                <p>
                    Dodaje naprawe
                </p>

                <a class="btn btn-default" href='@Url.Action("Create", "RepairModels")'>Click &raquo;</a>
                <a class="btn btn-default" href='@Url.Action("Index", "RepairModels")'>Spojrz istniejace &raquo;</a>
            </div>
        </div>
        </div>
        -->
}
else
{
    <div class="jumbotron">
        <h1>ClassicGarage</h1>
        <p class="lead">Aplikacja do zarządzania autami na zaliczenie ASP NET</p>

    </div>



    @Html.ActionLink("Zobacz Ogłoszenia", "AllNotice", "NoticeModels", null, new { @class = "btn btn-primary btn-lg" })

}