ClassicGarage/Models/RepairModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ClassicGarage.Models
{
    [Table("Repair")]
    public class RepairModel
    {

        public int ID { get; set; }
        
        public int? CarID { get; set; }
        [DisplayName("Nazwa")]
        public string Name { get; set; }
        [DisplayName("Opis")]
        public string Description { get; set; }
        [DisplayName("Cena")]
        public int? Cost { get; set; }
        
        public virtual CarModel Car { get; set; }
        
        public virtual ICollection<PartsModel> Part { get; set; }
    }
}

ClassicGarage/Controllers/RepairModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClassicGarage.DAL;
using ClassicGarage.Models;

namespace ClassicGarage.Controllers
{
    public class RepairModelsController : Controller
    {
        private GarageContext db = new GarageContext();

        // GET: RepairModels
        public ActionResult Index()
        {
            var repair = db.Repair.Include(r => r.Car);
            return View(repair.ToList());
        }

        // GET: RepairModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var Repair = db.Parts.Include(p => p.Repair).Where(p => p.RepairID == id);
            Session["RepairID"] = id;
            RepairModel nameRepair = db.Repair.Find(id);
            ViewBag.Description = nameRepair.Description;
            ViewBag.nameRepair = nameRepair.Name;
            ViewBag.Id = id;
            ViewBag.PriceRepair = nameRepair.Cost;
            
            if (Repair == null)
            {
                return HttpNotFound();
            }
            return View(Repair.ToList());
        }
        // GET: RepairModels/Repairs/5
        public ActionResult Repairs(int? id)
        {
            var Repair = db.Repair.Include(p => p.Car).Where(p => p.CarID == id);
            CarModel car = db.Car.Find(id);
            ViewBag.CarID = id;
            ViewBag.Car = car.Brand+" "+car.Model;
            return View(Repair.ToList());
        }

        // GET: RepairModels/Create
        public ActionResult Create(int? id)
        {
            ViewBag.CarID = id;
            return View();
        }

        // POST: RepairModels/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CarID,Name,Description,Cost")] RepairModel repairModel)
        {
            if (ModelState.IsValid)
            {
                db.Repair.Add(repairModel);
                db.SaveChanges();
                return RedirectToAction("Repairs",new { id = repairModel.CarID });
            }

            //ViewBag.CarID = new SelectList(db.Car, "ID", "Brand", repairModel.CarID);
            return View(repairModel);
        }

        // GET: RepairModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RepairModel repairModel = db.Repair.Find(id);
            if (repairModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarID = new SelectList(db.Car, "ID", "Brand", repairModel.CarID);
            return View(repairModel);
        }

        // POST: RepairModels/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CarID,Name,Description,Cost")] RepairModel repairModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(repairModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CarID = new SelectList(db.Car, "ID", "Brand", repairModel.CarID);
            return View(repairModel);
        }

        // GET: RepairModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RepairModel repairModel = db.Repair.Find(id);
            if (repairModel == null)
            {
                return HttpNotFound();
            }
            return View(repairModel);
        }

        // POST: RepairModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RepairModel repairModel = db.Repair.Find(id);
            db.Repair.Remove(repairModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClassicGarage/Views/RepairModels/Create.cshtml
@model ClassicGarage.Models.RepairModel

@{
    ViewBag.Title = "Naprawa";
}

<h2>Naprawa</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
   
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.Hidden("CarID", (object)ViewBag.CarID)
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Stwórz" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Wroc", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClassicGarage/Views/RepairModels/Delete.cshtml
@model ClassicGarage.Models.RepairModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RepairModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Car.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ClassicGarage/Views/RepairModels/Details.cshtml
@model IEnumerable<ClassicGarage.Models.PartsModel>

@{
    /**/

    ViewBag.Title = "Details";
}

<h2>Szczegóły</h2>

<div>

    <hr />
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">@Html.DisplayNameFor(Model => Model.Repair.Name)</th>
                <th scope="col">  Części</th>
                <th scope="col">  Opis</th>
                <th scope="col">Kwota całej naprawy</th>

            </tr>
        </thead>
        <tbody>

            <tr>
                <td>
                    <b> @ViewBag.nameRepair</b>
                </td>
                <td>
                    @foreach (var item_1 in Model)
                    {
                        <a href="@Url.Action("Details", "PartsModels",new { id = item_1.ID })" class="elements"><span>@Html.DisplayFor(Model => item_1.Name)</span></a>



                        <br />
                    }
                </td>
                <td>
                  @ViewBag.Description

                </td>
                <td>
                    @ViewBag.PriceRepair
                </td>
            </tr>






        </tbody>
    </table>

    @Html.ActionLink("Dodaj nową część", "Create", "PartsModels", new { id = ViewBag.Id }, new { @class = "btn btn-primary btn-lg" })

    
    <p>
        
    </p>

ClassicGarage/Views/RepairModels/Edit.cshtml
@model ClassicGarage.Models.RepairModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edycja</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RepairModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.CarID, "CarID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CarID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CarID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClassicGarage/Views/RepairModels/Index.cshtml
@model IEnumerable<ClassicGarage.Models.RepairModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Car.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Car.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cost)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

ClassicGarage/Views/RepairModels/Repairs.cshtml
@model IEnumerable<ClassicGarage.Models.RepairModel>
@{
    ViewBag.Title = "AllRepair";
}

<h2>Naprawy</h2>
<h4>
    @ViewBag.Car
</h4>
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">@Html.DisplayNameFor(model => model.Name) </th>
            <th scope="col"> </th>


        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>

                    @Html.DisplayFor(modelItem => item.Name)


                </td>
                <td>
                    <a href="@Url.Action("Details", "RepairModels",new { id = item.ID })" class="btn btn-warning">

                        <span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>
                    </a>
                </td>




            </tr>
        }
    </tbody>
</table>


@Html.ActionLink("Dodaj naprawę", "Create", "RepairModels", new { id = ViewBag.CarID }, new { @class = "btn btn-primary btn-lg" })

@Html.ActionLink("Lista czesci dla danego ałta", "Index", "PartsModels", new { id = ViewBag.CarID }, new { @class = "btn btn-primary btn-lg" })